//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKH_GS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class duty_View
    {
        public Nullable<System.DateTime> date { get; set; }
        public string weekDay { get; set; }
        public string typeDay { get; set; }
        public string duty_type_id { get; set; }
        public string duty_name { get; set; }
        public string duty_type { get; set; }
        public string duty_description { get; set; }
        public string duty_man { get; set; }
        public long id { get; set; }
    }
}
