//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKH_GS_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSdutyEntities : DbContext
    {
        public GSdutyEntities()
            : base("name=GSdutyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<date_type> date_type { get; set; }
        public virtual DbSet<division> divisions { get; set; }
        public virtual DbSet<duty_note> duty_note { get; set; }
        public virtual DbSet<duty_type> duty_type { get; set; }
        public virtual DbSet<duty_View> duty_View { get; set; }
        public virtual DbSet<duty_table> duty_table { get; set; }
    }
}
