//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKH_GS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_case
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public string sex { get; set; }
        public string chartNo { get; set; }
        public string history { get; set; }
        public string GSR { get; set; }
        public string GSVS { get; set; }
        public string PathoVS { get; set; }
        public Nullable<System.DateTime> meet_date { get; set; }
    }
}
