//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKH_GS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPRTODRF
    {
        public string ODR_LOGN { get; set; }
        public string ODR_CHRT { get; set; }
        public string ODR_TXDT { get; set; }
        public string ODR_OPRM { get; set; }
        public string ODR_DEPT { get; set; }
        public string ODR_PSRC { get; set; }
        public string ODR_BDNO { get; set; }
        public string ODR_EFLG { get; set; }
        public string ODR_IPNO { get; set; }
        public string ODR_AS_D { get; set; }
        public string ODR_AS_T { get; set; }
        public string ODR_AE_D { get; set; }
        public string ODR_AE_T { get; set; }
        public string ODR_IN_D { get; set; }
        public string ODR_IN_T { get; set; }
        public string ODR_OS_D { get; set; }
        public string ODR_OS_T { get; set; }
        public string ODR_OE_D { get; set; }
        public string ODR_OE_T { get; set; }
        public string ODR_OT_D { get; set; }
        public string ODR_OT_T { get; set; }
        public string ODR_OP_1 { get; set; }
        public string ODR_OP_2 { get; set; }
        public string ODR_KF_2 { get; set; }
        public string ODR_SK_2 { get; set; }
        public string ODR_OP_3 { get; set; }
        public string ODR_KF_3 { get; set; }
        public string ODR_SK_3 { get; set; }
        public string ODR_OP_4 { get; set; }
        public string ODR_KF_4 { get; set; }
        public string ODR_SK_4 { get; set; }
        public string ODR_M_DR { get; set; }
        public string ODR_DN_1 { get; set; }
        public string ODR_DN_2 { get; set; }
        public string ODR_WN_1 { get; set; }
        public string ODR_WN_2 { get; set; }
        public short ODR_AD_1 { get; set; }
        public short ODR_AD_2 { get; set; }
        public short ODR_AD_3 { get; set; }
        public short ODR_AD_4 { get; set; }
        public string ODR_PAYK { get; set; }
        public string ODR_OPID { get; set; }
        public string ODR_ANAM { get; set; }
        public string ODR_AN_D { get; set; }
        public string ODR_INDR { get; set; }
        public string ODR_ASA { get; set; }
        public string ODR_IRFG { get; set; }
        public string ODR_IDFC { get; set; }
        public string ODR_OPAG { get; set; }
        public string ODR_FAID { get; set; }
        public string ODR_DEAD { get; set; }
        public string ODR_SAT1 { get; set; }
        public string ODR_SAT2 { get; set; }
        public string ODR_SAT3 { get; set; }
        public string ODR_SAT4 { get; set; }
        public string ODR_SAT5 { get; set; }
        public string ODR_ANS1 { get; set; }
        public string ODR_ANS2 { get; set; }
        public string ODR_ANS3 { get; set; }
        public string ODR_ANS4 { get; set; }
        public string ODR_ANS5 { get; set; }
        public string ODR_M_D2 { get; set; }
        public string ODR_M_D3 { get; set; }
        public string ODR_M_D4 { get; set; }
        public string ODR_PKN1 { get; set; }
        public string ODR_PKN2 { get; set; }
        public string ODR_PKN3 { get; set; }
        public string ODR_PKN4 { get; set; }
        public string ODR_TIM1 { get; set; }
        public string ODR_TIM2 { get; set; }
        public string ODR_TIM3 { get; set; }
        public string ODR_TIM4 { get; set; }
        public string ODR_CHRF { get; set; }
        public string ODR_SPKD { get; set; }
        public int ODR_ORMT { get; set; }
        public int ODR_ANMT { get; set; }
        public string ODR_ANT1 { get; set; }
        public string ODR_ANT2 { get; set; }
        public string ODR_ANT3 { get; set; }
        public string ODR_WOUD { get; set; }
        public string ODR_ITE1 { get; set; }
        public string ODR_ITE2 { get; set; }
        public string ODR_ITE3 { get; set; }
        public string ODR_ITE4 { get; set; }
        public string ODR_NPRO { get; set; }
        public string ODR_PC01 { get; set; }
        public string ODR_PC02 { get; set; }
        public string ODR_PC03 { get; set; }
        public string ODR_PC04 { get; set; }
        public string ODR_PC05 { get; set; }
        public string ODR_PC06 { get; set; }
        public string ODR_PC07 { get; set; }
        public string ODR_PC08 { get; set; }
        public string ODR_PC09 { get; set; }
        public string ODR_PC10 { get; set; }
        public string ODR_PC11 { get; set; }
        public string ODR_PC12 { get; set; }
        public string ODR_PC13 { get; set; }
        public string ODR_PC14 { get; set; }
        public string ODR_PC15 { get; set; }
        public string ODR_PC16 { get; set; }
        public string ODR_PC17 { get; set; }
        public string ODR_PC18 { get; set; }
        public string ODR_PC19 { get; set; }
        public string ODR_PC20 { get; set; }
        public string ODR_PKN5 { get; set; }
        public string ODR_TIM5 { get; set; }
        public string ODR_PRDG { get; set; }
        public string ODR_FIND { get; set; }
        public string ODR_OPF { get; set; }
        public string ODR_OPP { get; set; }
        public string ODR_PODG { get; set; }
    }
}
