//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKH_GS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teach
    {
        public long id { get; set; }
        public Nullable<System.DateTime> teach_date { get; set; }
        public string weekDay { get; set; }
        public string teach_time { get; set; }
        public string activity_name { get; set; }
        public string learner { get; set; }
        public string supervisor { get; set; }
        public string location { get; set; }
    }
}
