//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKH_GS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public long id { get; set; }
        public Nullable<System.DateTime> team_date { get; set; }
        public Nullable<int> team_no { get; set; }
        public string vs { get; set; }
        public string fellow { get; set; }
        public string cr { get; set; }
        public string r { get; set; }
        public string pgy { get; set; }
        public string intern { get; set; }
        public string clerk { get; set; }
    }
}
