//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKH_GS_MVC.SKH_Check {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SKH_Check.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SKH_GS_MVC.SKH_Check.HelloWorldResponse HelloWorld(SKH_GS_MVC.SKH_Check.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SKH_GS_MVC.SKH_Check.HelloWorldResponse> HelloWorldAsync(SKH_GS_MVC.SKH_Check.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_AUTH", ReplyAction="*")]
        SKH_GS_MVC.SKH_Check.CHECK_AUTHResponse CHECK_AUTH(SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_AUTH", ReplyAction="*")]
        System.Threading.Tasks.Task<SKH_GS_MVC.SKH_Check.CHECK_AUTHResponse> CHECK_AUTHAsync(SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SKH_GS_MVC.SKH_Check.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SKH_GS_MVC.SKH_Check.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SKH_GS_MVC.SKH_Check.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SKH_GS_MVC.SKH_Check.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CHECK_AUTHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CHECK_AUTH", Namespace="http://tempuri.org/", Order=0)]
        public SKH_GS_MVC.SKH_Check.CHECK_AUTHRequestBody Body;
        
        public CHECK_AUTHRequest() {
        }
        
        public CHECK_AUTHRequest(SKH_GS_MVC.SKH_Check.CHECK_AUTHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CHECK_AUTHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EMID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PWD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RETURN_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RETURN_ACC;
        
        public CHECK_AUTHRequestBody() {
        }
        
        public CHECK_AUTHRequestBody(string EMID, string PWD, string RETURN_NAME, string RETURN_ACC) {
            this.EMID = EMID;
            this.PWD = PWD;
            this.RETURN_NAME = RETURN_NAME;
            this.RETURN_ACC = RETURN_ACC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CHECK_AUTHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CHECK_AUTHResponse", Namespace="http://tempuri.org/", Order=0)]
        public SKH_GS_MVC.SKH_Check.CHECK_AUTHResponseBody Body;
        
        public CHECK_AUTHResponse() {
        }
        
        public CHECK_AUTHResponse(SKH_GS_MVC.SKH_Check.CHECK_AUTHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CHECK_AUTHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CHECK_AUTHResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RETURN_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RETURN_ACC;
        
        public CHECK_AUTHResponseBody() {
        }
        
        public CHECK_AUTHResponseBody(bool CHECK_AUTHResult, string RETURN_NAME, string RETURN_ACC) {
            this.CHECK_AUTHResult = CHECK_AUTHResult;
            this.RETURN_NAME = RETURN_NAME;
            this.RETURN_ACC = RETURN_ACC;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SKH_GS_MVC.SKH_Check.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SKH_GS_MVC.SKH_Check.ServiceSoap>, SKH_GS_MVC.SKH_Check.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SKH_GS_MVC.SKH_Check.HelloWorldResponse SKH_GS_MVC.SKH_Check.ServiceSoap.HelloWorld(SKH_GS_MVC.SKH_Check.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SKH_GS_MVC.SKH_Check.HelloWorldRequest inValue = new SKH_GS_MVC.SKH_Check.HelloWorldRequest();
            inValue.Body = new SKH_GS_MVC.SKH_Check.HelloWorldRequestBody();
            SKH_GS_MVC.SKH_Check.HelloWorldResponse retVal = ((SKH_GS_MVC.SKH_Check.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SKH_GS_MVC.SKH_Check.HelloWorldResponse> SKH_GS_MVC.SKH_Check.ServiceSoap.HelloWorldAsync(SKH_GS_MVC.SKH_Check.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SKH_GS_MVC.SKH_Check.HelloWorldResponse> HelloWorldAsync() {
            SKH_GS_MVC.SKH_Check.HelloWorldRequest inValue = new SKH_GS_MVC.SKH_Check.HelloWorldRequest();
            inValue.Body = new SKH_GS_MVC.SKH_Check.HelloWorldRequestBody();
            return ((SKH_GS_MVC.SKH_Check.ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SKH_GS_MVC.SKH_Check.CHECK_AUTHResponse SKH_GS_MVC.SKH_Check.ServiceSoap.CHECK_AUTH(SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest request) {
            return base.Channel.CHECK_AUTH(request);
        }
        
        public bool CHECK_AUTH(string EMID, string PWD, ref string RETURN_NAME, ref string RETURN_ACC) {
            SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest inValue = new SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest();
            inValue.Body = new SKH_GS_MVC.SKH_Check.CHECK_AUTHRequestBody();
            inValue.Body.EMID = EMID;
            inValue.Body.PWD = PWD;
            inValue.Body.RETURN_NAME = RETURN_NAME;
            inValue.Body.RETURN_ACC = RETURN_ACC;
            SKH_GS_MVC.SKH_Check.CHECK_AUTHResponse retVal = ((SKH_GS_MVC.SKH_Check.ServiceSoap)(this)).CHECK_AUTH(inValue);
            RETURN_NAME = retVal.Body.RETURN_NAME;
            RETURN_ACC = retVal.Body.RETURN_ACC;
            return retVal.Body.CHECK_AUTHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SKH_GS_MVC.SKH_Check.CHECK_AUTHResponse> SKH_GS_MVC.SKH_Check.ServiceSoap.CHECK_AUTHAsync(SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest request) {
            return base.Channel.CHECK_AUTHAsync(request);
        }
        
        public System.Threading.Tasks.Task<SKH_GS_MVC.SKH_Check.CHECK_AUTHResponse> CHECK_AUTHAsync(string EMID, string PWD, string RETURN_NAME, string RETURN_ACC) {
            SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest inValue = new SKH_GS_MVC.SKH_Check.CHECK_AUTHRequest();
            inValue.Body = new SKH_GS_MVC.SKH_Check.CHECK_AUTHRequestBody();
            inValue.Body.EMID = EMID;
            inValue.Body.PWD = PWD;
            inValue.Body.RETURN_NAME = RETURN_NAME;
            inValue.Body.RETURN_ACC = RETURN_ACC;
            return ((SKH_GS_MVC.SKH_Check.ServiceSoap)(this)).CHECK_AUTHAsync(inValue);
        }
    }
}
